### PR TITLE
Add inet DBType

### PR DESCRIPTION
**Pull request by JonathanLorimer**
This PR adds a DBType instance for `NetAddr IP`, which is the default type that hasql uses for the postgres `inet` type. In the future I would also like to add support for `SockAddr` from the `network` package.

I'm a new committer and would appreciate any feedback, especially nitpicks and stylistic comments.

As a side note, I was wondering if you have a public nix cache. I am trying to set up my dev environment to test, but haskell.nix is trying to rebuild the world!

### CODE REVIEW

**Comment by shane-circuithub** [comment]
This looks good to me. I didn't know Postgres natively supported IP address types.

**Comment by ocharles** [comment]
Yep, that sounds good to me. @JonathanLorimer if you could change that lower bound, we'll get this merged. Thanks for your contribution!

**Comment by ocharles** [comment]
> As a side note, I was wondering if you have a public nix cache. I am trying to set up my dev environment to test, but haskell.nix is trying to rebuild the world!

You should be able to `cachix use rel8`

**Comment by JonathanLorimer** [comment]
> > As a side note, I was wondering if you have a public nix cache. I am trying to set up my dev environment to test, but haskell.nix is trying to rebuild the world!
> 
> You should be able to `cachix use rel8`

unfortunately I get this when I run `cachix use rel8`: `Binary cache rel8 doesn't exist or it's private and you don't have access it`

**Comment by JonathanLorimer** [comment]
@shane-circuithub or @ocharles can you approve the workflow? Tests are passing locally.

**Pull request merged**
