### PR TITLE
Use less Opaleye internals in aggregation

### PR DESCRIPTION
**Pull request by tomjaguarpaw**
Would it be OK to do this, to depend on less Opaleye internals?

### CODE REVIEW

**Comment by tomjaguarpaw** [comment]
Hey folks, any thoughts on this? This would allow me to rearrange the Opaleye aggregate internals, which are in need of clarification.

**Comment by ocharles** [comment]
@shane-circuithub Could you take a look at this?

**Comment by shane-circuithub** [comment]
I'm generally in favour of this. I know we currently don't use the `ordering` field of our `Aggregator` type, but we have used it in the past. Is there an equivalent of `distinctAggregator` for adding an ordering @tomjaguarpaw ?

**Comment by shane-circuithub** [comment]
Yep, that looks like what I mean. In that case I don't see any downside to this.

**Comment by ocharles** [comment]
Thanks @shane-circuithub!

**Pull request merged**
