### PR TITLE
Support opaleye 0.8.0.0

### PR DESCRIPTION
**Pull request by tomjaguarpaw**
I believe this is all that is required

### CODE REVIEW

**Comment by tomjaguarpaw** [comment]
See also https://github.com/tomjaguarpaw/haskell-opaleye/issues/534

**Comment by tomjaguarpaw** [comment]
(0.8 is not released yet, but is imminent.)

**Comment by ocharles** [comment]
Oh wow, I missed this PR - thanks for taking a look! I'll bump Haskell.nix and see if this passes CI.

**Comment by ocharles** [comment]
Thanks! Merged and will be released as 1.2.1.0.

**Pull request merged**
