### PR TITLE
fix: JSONEncoded should be encoded as json not jsonb

### LINKED ISSUE #344: `JSONEncoded` produces `jsonb` rather than the documented `json`
It seems to delegate to `Aeson.Value`'s `DBType` via `parseJSON`/`toJSON`, but `Aeson.Value`'s `DBType` is `jsonb`. This means (as far as I can tell) the behaviour is the same as `JSONBEncoded`.

### PR DESCRIPTION
**Pull request by TeofilC**
Resolves #344

### CODE REVIEW

**Comment by TeofilC** [comment]
This is a breaking change

**Comment by ocharles** [comment]
I have a feeling we are relying on `Value` being `jsonb` at the moment in CircuitHub code. Could you check that? Hopefully grepping for `Column f Value` and then checking the current schema will point you in the right direction. Generally speaking I think the current behavior is correct - the PostgreSQL `json` type preserves whitespace (iirc), but `Value` doesn't - so it's not quite the same type.

**Comment by TeofilC** [comment]
Maybe the right thing to do in that case is have `JSONEncoded` not go directly via the `Value` instance

**Comment by TeofilC** [comment]
How about this instead @ocharles ?

**Comment by ocharles** [comment]
Yea this looks good - I'll have to remind myself how `TypeInformation` works! Could we write any tests for this?

**Comment by TeofilC** [comment]
Actually I'm going to inline some of this to make it a bit clearer and mirror JSONBEncoded

**Comment by ocharles** [comment]
SGTM!

**Comment by TeofilC** [comment]
I've added a test case as well

**Review by ocharles — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
