### PR TITLE
Release 1.5.0.0

### LINKED ISSUE #293: New Hackage release?
I love the additions you've made into `master`, especially the fix for https://github.com/circuithub/rel8/issues/228. Any timeline on when those might show up on Hackage?

My main use case is that I'd like to be able to see the rendered Haddock on the package site. My team is currently using a commit off of `master`, and newbies occasionally trip over the outdated documentation.

### PR DESCRIPTION
**Pull request by ocharles**
Fixes #293 and #288.

### CODE REVIEW

**Comment by ocharles** [comment]
@shane-circuithub I see that at CircuitHub we're also running https://github.com/circuithub/rel8/pull/284. Shall we call that tested and also merge that into this release?

**Comment by ocharles** [comment]
I would also like to see this build with all outdated deps: https://packdeps.haskellers.com/feed?needle=rel8

**Comment by ocharles** [comment]
Ok, upstream deps aren't ready for 9.8, so the only outdated dep we need to address is Opaleye, which is already fixed in `master`. I think we're good to go!

**Review by shane-circuithub — APPROVED** [review]

**Comment by shane-circuithub** [comment]
Do note that the "aggregation" section of the cookbook is completely wrong though, it dates from the time we had an `Apply` interface for `Aggregate`, before the first release. It's even more wrong now with the changes made to aggregation in this release. Maybe we should fix that?

**Comment by ocharles** [comment]
@shane-circuithub sorry for the delayed reply! I don't see a need to release ASAP, so I think we should wait for the Opaleye changes to land first.

**Comment by sir4ur0n** [comment]
What is the status of the 1.5.0.0 release please?
The [latest comment](https://github.com/circuithub/rel8/pull/298#issuecomment-1893550260) suggests this is waiting for https://github.com/circuithub/rel8/pull/298 to be merged and released, however this PR is closed, not merged.

On my project, we are waiting for some features present on `master` but not in a released version (most notably, the `loop` function, equivalent of `WITH RECURSIVE`), so I would like to check this releasing PR is not in some sort of deadlock :grin:

**Comment by ocharles** [comment]
Unfortunately just waiting on me to find the time to get the release out! Thanks for the nudge, I'll try and give this some more time soon

**Comment by sir4ur0n** [comment]
Awesome, thank you! :pray:

**Pull request merged**
