### PR TITLE
Explicit Inserts

### LINKED ISSUE #46: Confusing error with `HList f (Column f X)`
I wrote

```haskell
data BinAndLots f = BinAndLots
  { binId :: Column f BinId
  , lotIds :: HList f (Column f LotId)
  , binType :: Column f BinType
  } deriving (Generic, Rel8able)
```

And got:

```
src/CircuitHub/Persistence/OrderPlacementDetails.hs:162:24: error:
    • Couldn't match type ‘rel8-0.1.0.0:Rel8.Expr.Expr’
                     with ‘rel8-0.1.0.0:Rel8.Schema.Insert.Insert’
        arising from a functional dependency between:
          constraint ‘rel8-0.1.0.0:Rel8.Table.Table
                        rel8-0.1.0.0:Rel8.Schema.Insert.Insert
                        (rel8-0.1.0.0:Rel8.Expr.Expr LotId)’
            arising from the 'deriving' clause of a data type declaration
          instance ‘rel8-0.1.0.0:Rel8.Table.Table
                      rel8-0.1.0.0:Rel8.Expr.Expr (rel8-0.1.0.0:Rel8.Expr.Expr a)’
            at <no location info>
    • When deriving the instance for (Rel8able BinAndLots)
    |
162 |   } deriving (Generic, Rel8able)
    |                        ^^^^^^^^

src/CircuitHub/Persistence/OrderPlacementDetails.hs:162:24: error:
    • Couldn't match type ‘rel8-0.1.0.0:Rel8.Expr.Expr’
                     with ‘rel8-0.1.0.0:Rel8.Schema.Insert.Insert’
        arising from a functional dependency between:
          constraint ‘rel8-0.1.0.0:Rel8.Table.Table
                        rel8-0.1.0.0:Rel8.Schema.Insert.Insert
                        (rel8-0.1.0.0:Rel8.Expr.Expr LotId)’
            arising from the 'deriving' clause of a data type declaration
          instance ‘rel8-0.1.0.0:Rel8.Table.Table
                      rel8-0.1.0.0:Rel8.Expr.Expr (rel8-0.1.0.0:Rel8.Expr.Expr a)’
            at <no location info>
    • When deriving the instance for (Rel8able BinAndLots)
    |
162 |   } deriving (Generic, Rel8able)
    |                        ^^^^^^^^

src/CircuitHub/Persistence/OrderPlacementDetails.hs:162:24: error:
    • Couldn't match type ‘rel8-0.1.0.0:Rel8.Expr.Expr’
                     with ‘rel8-0.1.0.0:Rel8.Schema.Insert.Insert’
        arising from a functional dependency between:
          constraint ‘rel8-0.1.0.0:Rel8.Table.Table
                        rel8-0.1.0.0:Rel8.Schema.Insert.Insert
                        (rel8-0.1.0.0:Rel8.Expr.Expr LotId)’
            arising from the 'deriving' clause of a data type declaration
          instance ‘rel8-0.1.0.0:Rel8.Table.Table
                      rel8-0.1.0.0:Rel8.Expr.Expr (rel8-0.1.0.0:Rel8.Expr.Expr a)’
            at <no location info>
    • When deriving the instance for (Rel8able BinAndLots)
    |
162 |   } deriving (Generic, Rel8able)
    |                        ^^^^^^^^

src/CircuitHub/Persistence/OrderPlacementDetails.hs:162:24: error:
    • Couldn't match type ‘rel8-0.1.0.0:Rel8.Expr.Expr’
                     with ‘rel8-0.1.0.0:Rel8.Schema.Insert.Insert’
        arising from a functional dependency between:
          constraint ‘rel8-0.1.0.0:Rel8.Table.Table
                        rel8-0.1.0.0:Rel8.Schema.Insert.Insert
                        (rel8-0.1.0.0:Rel8.Expr.Expr LotId)’
            arising from the 'deriving' clause of a data type declaration
          instance ‘rel8-0.1.0.0:Rel8.Table.Table
                      rel8-0.1.0.0:Rel8.Expr.Expr (rel8-0.1.0.0:Rel8.Expr.Expr a)’
            at <no location info>
    • When deriving the instance for (Rel8able BinAndLots)
    |
162 |   } deriving (Generic, Rel8able)
    |                        ^^^^^^^^
```

It would be good if this either just worked, or gave a much more exact error message.

### PR DESCRIPTION
**Pull request by shane-circuithub**
This would fix #46, but it would break most existing code that uses `insert`.

### CODE REVIEW

**Comment by ocharles** [comment]
> This would fix #46

What error do we get with this change? Or would it not error at all, and now work?

**Comment by shane-circuithub** [comment]
It now just works.

**Comment by shane-circuithub** [comment]
(as you can see from the change to `Rel8.Generic.Rel8able.Test`)

**Review by ocharles — APPROVED** [review]
Sweet!

**Comment by shane-circuithub** [comment]
Closing in favour of #49.

**Pull request closed without merging**
